### ISSUE TITLE
Connection 500 Error

### ISSUE THREAD

**Issue by Tanych** [gwu-libraries/sfm-weibo-harvester#3]
## Situation
* Running frequency: 20min per collection
* Running period: 5 days

The testing weibo harverster keep running for about 5 days. It occurs a http 500 error. Not sure  whether it happens occasionally or frequently but logs only catch one time. Keep running get more data.
## Logs

```bash
sfmweiboharvester_1 | 2016-02-20 06:57:04,712: sfmutils.warcprox --> Executing warcprox -c /tmp/tmpff670w/warcprox-ca.pem --certs-dir /tmp/tmpff670w --dedup-db-file /dev/null -d /tmp/test_3NhOA7K -n test_3 -p 8000 -z --rollover-time 900 --rollover-idle-time 930 -r 100000000 --record-rollover-time 300 -v
sfmweiboharvester_1 | 2016-02-20 06:57:04,900 3527 INFO MainThread root.main(main.py:110) deduplication disabled
sfmweiboharvester_1 | 2016-02-20 06:57:05,257 3527 INFO MainThread warcprox.warcprox.WarcProxy.server_activate(warcprox.py:327) WarcProxy listening on 127.0.0.1:8000
sfmweiboharvester_1 | 2016-02-20 06:57:05,257 3527 INFO MainThread warcprox.controller.WarcproxController.run_until_shutdown(controller.py:46) Running until shutdown
sfmweiboharvester_1 | 2016-02-20 06:57:05,259 3527 INFO WarcWriterThread warcprox.warcwriter.WarcWriterThread.run(warcwriter.py:336) WarcWriterThread starting, directory=/tmp/test_3NhOA7K gzip=True rollover_size=1000000000 rollover_idle_time=930 prefix=test_3 port=8000 rollover_time=900
sfmweiboharvester_1 | 2016-02-20 06:57:05,259 3527 INFO MainThread warcprox.controller.WarcproxController.run_until_shutdown(controller.py:59) SIGTERM will initiate graceful shutdown
sfmweiboharvester_1 | 2016-02-20 06:57:09,721: weibowarc --> creating client session with api_key=3252156855
sfmweiboharvester_1 | 2016-02-20 06:57:09,723: __main__ --> Harvest type is weibo_timeline
sfmweiboharvester_1 | 2016-02-20 06:57:09,724: weibowarc --> starting search for max_id:None, since_id:3944602111559332.
sfmweiboharvester_1 | 2016-02-20 06:57:09,725: requests.packages.urllib3.connectionpool --> Starting new HTTPS connection (1): api.weibo.com
sfmweiboharvester_1 | 2016-02-20 06:57:25,209 3527 ERROR Thread-1 warcprox.warcprox.WarcProxyHandler.log_error(mitmproxy.py:143) localhost - - [20/Feb/2016 06:57:25] code 500, message [Errno -2] Name or service not known
sfmweiboharvester_1 | 2016-02-20 06:57:25,210 3527 INFO Thread-1 warcprox.warcprox.WarcProxyHandler.log_message(mitmproxy.py:147) WarcProxyHandler localhost - - [20/Feb/2016 06:57:25] "CONNECT api.weibo.com:443 HTTP/1.0" 500 -
sfmweiboharvester_1 | 2016-02-20 06:57:25,211: weibowarc --> caught connection error HTTPSConnectionPool(host='api.weibo.com', port=443): Max retries exceeded with url: /2/statuses/friends_timeline.json?access_token=2.00kQCxKGpYiFYDc41039481c0wvwei&count=100&page=1&since_id=3944602111559332 (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 500 [Errno -2] Name or service not known',)))
sfmweiboharvester_1 | 2016-02-20 06:57:25,212: weibowarc --> creating client session with api_key=3252156855
sfmweiboharvester_1 | 2016-02-20 06:57:25,214: requests.packages.urllib3.connectionpool --> Starting new HTTPS connection (1): api.weibo.com
sfmweiboharvester_1 | 2016-02-20 06:57:40,283 3527 ERROR Thread-2 warcprox.warcprox.WarcProxyHandler.log_error(mitmproxy.py:143) localhost - - [20/Feb/2016 06:57:40] code 500, message [Errno -2] Name or service not known
sfmweiboharvester_1 | 2016-02-20 06:57:40,284 3527 INFO Thread-2 warcprox.warcprox.WarcProxyHandler.log_message(mitmproxy.py:147) WarcProxyHandler localhost - - [20/Feb/2016 06:57:40] "CONNECT api.weibo.com:443 HTTP/1.0" 500 -
sfmweiboharvester_1 | 2016-02-20 06:57:40,285: weibowarc --> caught connection error HTTPSConnectionPool(host='api.weibo.com', port=443): Max retries exceeded with url: /2/statuses/friends_timeline.json?access_token=2.00kQCxKGpYiFYDc41039481c0wvwei&count=100&page=1&since_id=3944602111559332 (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 500 [Errno -2] Name or service not known',)))
sfmweiboharvester_1 | 2016-02-20 06:57:40,285: weibowarc --> creating client session with api_key=3252156855
sfmweiboharvester_1 | 2016-02-20 06:57:40,287: requests.packages.urllib3.connectionpool --> Starting new HTTPS connection (1): api.weibo.com
sfmweiboharvester_1 | 2016-02-20 06:57:55,357 3527 ERROR Thread-3 warcprox.warcprox.WarcProxyHandler.log_error(mitmproxy.py:143) localhost - - [20/Feb/2016 06:57:55] code 500, message [Errno -2] Name or service not known
sfmweiboharvester_1 | 2016-02-20 06:57:55,358 3527 INFO Thread-3 warcprox.warcprox.WarcProxyHandler.log_message(mitmproxy.py:147) WarcProxyHandler localhost - - [20/Feb/2016 06:57:55] "CONNECT api.weibo.com:443 HTTP/1.0" 500 -
sfmweiboharvester_1 | 2016-02-20 06:57:55,359: weibowarc --> caught connection error HTTPSConnectionPool(host='api.weibo.com', port=443): Max retries exceeded with url: /2/statuses/friends_timeline.json?access_token=2.00kQCxKGpYiFYDc41039481c0wvwei&count=100&page=1&since_id=3944602111559332 (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 500 [Errno -2] Name or service not known',)))
sfmweiboharvester_1 | 2016-02-20 06:57:55,359: weibowarc --> creating client session with api_key=3252156855
sfmweiboharvester_1 | 2016-02-20 06:57:55,359 3527 WARNING Thread-3 warcprox.warcprox.WarcProxyHandler.do_CONNECT(mitmproxy.py:91) failed to send error response ([Errno -2] Name or service not known) to proxy client: [Errno 32] Broken pipe
sfmweiboharvester_1 | Traceback (most recent call last):
sfmweiboharvester_1 |   File "/usr/local/lib/python2.7/SocketServer.py", line 599, in process_request_thread
sfmweiboharvester_1 | 2016-02-20 06:57:55,361: requests.packages.urllib3.connectionpool --> Starting new HTTPS connection (1): api.weibo.com
sfmweiboharvester_1 |     self.finish_request(request, client_address)
sfmweiboharvester_1 |   File "/usr/local/lib/python2.7/SocketServer.py", line 334, in finish_request
sfmweiboharvester_1 |     self.RequestHandlerClass(request, client_address, self)
sfmweiboharvester_1 |   File "/usr/local/lib/python2.7/site-packages/warcprox/mitmproxy.py", line 25, in __init__
sfmweiboharvester_1 |     http_server.BaseHTTPRequestHandler.__init__(self, request, client_address, server)
sfmweiboharvester_1 |   File "/usr/local/lib/python2.7/SocketServer.py", line 657, in __init__
sfmweiboharvester_1 |     self.finish()
sfmweiboharvester_1 |   File "/usr/local/lib/python2.7/SocketServer.py", line 716, in finish
sfmweiboharvester_1 |     self.wfile.close()
sfmweiboharvester_1 |   File "/usr/local/lib/python2.7/socket.py", line 283, in close
sfmweiboharvester_1 |     self.flush()
sfmweiboharvester_1 |   File "/usr/local/lib/python2.7/socket.py", line 307, in flush
sfmweiboharvester_1 |     self._sock.sendall(view[write_offset:write_offset+buffer_size])
sfmweiboharvester_1 | error: [Errno 32] Broken pipe
sfmweiboharvester_1 | ----------------------------------------
sfmweiboharvester_1 | Exception happened during processing of request from ('127.0.0.1', 53644)
```

**Comment by Tanych** [comment]
Slow down to 20min per request! Catching the HTTP 403 and API 10022, 10023, 10024 Error of rate limit. Sleep until it works.
