### ISSUE TITLE
Http Response 504 Error

### ISSUE THREAD

**Issue by Tanych** [gwu-libraries/sfm-weibo-harvester#4]
## Situation
* Running frequency: 5min per collection
* Running period: 2 days

I am trying to use another account to keep collecting, but it returns the same error. It might be something wrong the REST service. Also, it could be some limitaions for the request ip. After stoping collection for one night, it seems work well.

## Logs
```bash
sfmweiboharvester_1 | 2016-02-13 04:27:52,312 27 DEBUG Thread-3 warcprox.warcprox.WarcProxyHandler._proxy_request(warcprox.py:226) Record size: 343. Max is 100000000.
sfmweiboharvester_1 | 2016-02-13 04:27:52,313 27 INFO Thread-3 warcprox.warcprox.WarcProxyHandler.log_message(mitmproxy.py:147) WarcProxyHandler localhost - - [13/Feb/2016 04:27:52] "GET /2/statuses/friends_timeline.json?access_token=2.00kQCxKGpYiFYDc41039481c0wvwei&count=100&max_id=3941747966905637&page=1 HTTP/1.1" 504 343
sfmweiboharvester_1 | 2016-02-13 04:27:52,315: sfmutils.warcprox --> Shutting down warcprox
sfmrabbit_1         | =INFO REPORT==== 13-Feb-2016::04:26:51 ===
sfmweiboharvester_1 | 2016-02-13 04:27:52,315: sfmutils.warcprox --> Terminating warcprox
sfmweiboharvester_1 | 2016-02-13 04:27:52,316: sfmutils.warcprox --> Waiting for warcprox to terminate
sfmweiboharvester_1 | 2016-02-13 04:27:52,329 27 INFO WarcWriterThread warcprox.warcwriter.WarcWriterThread.run(warcwriter.py:343) recorded_url.warcprox_meta={} for https://api.weibo.com/2/statuses/friends_timeline.json?access_token=2.00kQCxKGpYiFYDc41039481c0wvwei&count=100&max_id=3941747966905637&page=1
sfmweiboharvester_1 | 2016-02-13 04:27:52,330 27 DEBUG WarcWriterThread warcprox.warcwriter.WarcWriter.write_records(warcwriter.py:311) wrote warc record: warc_type=response content_length=343 url=https://api.weibo.com/2/statuses/friends_timeline.json?access_token=2.00kQCxKGpYiFYDc41039481c0wvwei&count=100&max_id=3941747966905637&page=1 warc=/tmp/test_3e2sjzp/test_3-20160213042743902-00000-27-dddc5b208b96-8000.warc.gz.open offset=83651
sfmweiboharvester_1 | 2016-02-13 04:27:52,331 27 DEBUG WarcWriterThread warcprox.warcwriter.WarcWriter.write_records(warcwriter.py:311) wrote warc record: warc_type=request content_length=238 url=https://api.weibo.com/2/statuses/friends_timeline.json?access_token=2.00kQCxKGpYiFYDc41039481c0wvwei&count=100&max_id=3941747966905637&page=1 warc=/tmp/test_3e2sjzp/test_3-20160213042743902-00000-27-dddc5b208b96-8000.warc.gz.open offset=84292
sfmweiboharvester_1 | 2016-02-13 04:27:52,331 27 INFO WarcWriterThread warcprox.warcwriter.WarcWriterThread.run(warcwriter.py:361) WarcWriterThread shutting down
sfmweiboharvester_1 | 2016-02-13 04:27:52,331 27 INFO WarcWriterThread warcprox.warcwriter.WarcWriter.close_writer(warcwriter.py:219) closing test_3-20160213042743902-00000-27-dddc5b208b96-8000.warc.gz
sfmrabbit_1         | Statistics database started.
sfmweiboharvester_1 | 2016-02-13 04:27:52,402 27 INFO MainThread warcprox.warcprox.WarcProxy.server_close(warcprox.py:330) WarcProxy shutting down
sfmweiboharvester_1 | 2016-02-13 04:27:52,416: sfmutils.warcprox --> warcprox terminated
sfmweiboharvester_1 | 2016-02-13 04:27:52,417: sfmutils.harvester --> Unknown error raised during harvest
sfmweiboharvester_1 | Traceback (most recent call last):
sfmweiboharvester_1 |   File "/opt/sfm-utils/sfmutils/harvester.py", line 194, in on_message
sfmweiboharvester_1 |     self.harvest_seeds()
sfmweiboharvester_1 |   File "weibo_harvester.py", line 26, in harvest_seeds
sfmweiboharvester_1 |     self.search_timeline()
sfmweiboharvester_1 |   File "weibo_harvester.py", line 35, in search_timeline
sfmrabbit_1         |  completed with 6 plugins.
sfmrabbit_1         | 
sfmrabbit_1         | =INFO REPORT==== 13-Feb-2016::04:26:52 ===
sfmrabbit_1         | Server startup complete; 6 plugins started.
sfmrabbit_1         |  * rabbitmq_management
sfmrabbit_1         |  * rabbitmq_web_dispatch
sfmrabbit_1         |  * webmachine
sfmrabbit_1         |  * rabbitmq_management_agent
sfmrabbit_1         |  * amqp_client
sfmrabbit_1         |  * mochiweb
sfmrabbit_1         | 
sfmrabbit_1         | =INFO REPORT==== 13-Feb-2016::04:27:14 ===
sfmrabbit_1         | accepting AMQP connection <0.574.0> (172.17.0.3:38937 -> 172.17.0.2:5672)
sfmrabbit_1         | 
sfmrabbit_1         | =INFO REPORT==== 13-Feb-2016::04:27:35 ===
sfmrabbit_1         | accepting AMQP connection <0.770.0> (172.17.0.3:38943 -> 172.17.0.2:5672)
sfmrabbit_1         | 
sfmrabbit_1         | =INFO REPORT==== 13-Feb-2016::04:27:35 ===
sfmrabbit_1         | closing AMQP connection <0.770.0> (172.17.0.3:38943 -> 172.17.0.2:5672)
sfmrabbit_1         | 
sfmrabbit_1         | =INFO REPORT==== 13-Feb-2016::04:27:35 ===
sfmrabbit_1         | accepting AMQP connection <0.798.0> (172.17.0.3:38944 -> 172.17.0.2:5672)
sfmrabbit_1         | 
sfmrabbit_1         | =INFO REPORT==== 13-Feb-2016::04:27:45 ===
sfmrabbit_1         | accepting AMQP connection <0.767.0> (172.17.0.3:38942 -> 172.17.0.2:5672)
sfmrabbit_1         | 
sfmrabbit_1         | =ERROR REPORT==== 13-Feb-2016::04:27:45 ===
sfmrabbit_1         | closing AMQP connection <0.767.0> (172.17.0.3:38942 -> 172.17.0.2:5672):
sfmrabbit_1         | {handshake_timeout,handshake}
sfmrabbit_1         | 
sfmrabbit_1         | =INFO REPORT==== 13-Feb-2016::04:27:52 ===
sfmrabbit_1         | accepting AMQP connection <0.973.0> (172.17.0.3:38955 -> 172.17.0.2:5672)
sfmrabbit_1         | 
sfmweiboharvester_1 |     max_weibo_id = self._process_weibos(self.weibowarc.search_friendships(since_id=since_id))
sfmweiboharvester_1 |   File "weibo_harvester.py", line 51, in _process_weibos
sfmweiboharvester_1 |     for count, weibo in enumerate(weibos):
sfmweiboharvester_1 |   File "/opt/sfm-weibo-harvester/weibowarc.py", line 249, in search_friendships
sfmweiboharvester_1 |     resp = self.get(friendships_url, **params)
sfmweiboharvester_1 |   File "/opt/sfm-weibo-harvester/weibowarc.py", line 180, in new_f
sfmrabbit_1         | =INFO REPORT==== 13-Feb-2016::04:27:52 ===
sfmweiboharvester_1 |     return fun(self, *args, **kwargs)
sfmrabbit_1         | closing AMQP connection <0.798.0> (172.17.0.3:38944 -> 172.17.0.2:5672)
sfmweiboharvester_1 |   File "/opt/sfm-weibo-harvester/weibowarc.py", line 283, in get
sfmweiboharvester_1 |     return self.client.get(*args, **kwargs)
sfmweiboharvester_1 |   File "/usr/local/lib/python2.7/site-packages/weibo.py", line 106, in get
sfmweiboharvester_1 |     res = json.loads(self.session.get(url, params=kwargs).text)
sfmweiboharvester_1 |   File "/usr/local/lib/python2.7/json/__init__.py", line 339, in loads
sfmweiboharvester_1 |     return _default_decoder.decode(s)
sfmweiboharvester_1 |   File "/usr/local/lib/python2.7/json/decoder.py", line 364, in decode
sfmweiboharvester_1 |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
sfmweiboharvester_1 |   File "/usr/local/lib/python2.7/json/decoder.py", line 382, in raw_decode
sfmweiboharvester_1 |     raise ValueError("No JSON object could be decoded")
sfmweiboharvester_1 | ValueError: No JSON object could be decoded
sfmweiboharvester_1 | 2016-02-13 04:27:52,419: sfmutils.harvester --> Sending message to sfm_exchange with routing_key harvest.status.weibo.weibo_timeline. The body is: {
sfmweiboharvester_1 |     "status": "completed failure", 
sfmweiboharvester_1 |     "warnings": [], 
sfmweiboharvester_1 |     "infos": [], 
sfmweiboharvester_1 |     "id": "test:3", 
sfmweiboharvester_1 |     "errors": [
sfmweiboharvester_1 |         {
sfmweiboharvester_1 |             "message": "No JSON object could be decoded", 
sfmweiboharvester_1 |             "code": "unknown_error"
sfmweiboharvester_1 |         }
sfmweiboharvester_1 |     ], 
sfmweiboharvester_1 |     "uids": {}, 
sfmweiboharvester_1 |     "token_updates": {}, 
sfmweiboharvester_1 |     "date_ended": "2016-02-13T04:27:52.418879", 
sfmweiboharvester_1 |     "summary": {
sfmweiboharvester_1 |         "weibo": 150
sfmweiboharvester_1 |     }, 
sfmweiboharvester_1 |     "date_started": "2016-02-13T04:27:35.762826", 
sfmweiboharvester_1 |     "warcs": {
sfmweiboharvester_1 |         "count": 0, 
sfmweiboharvester_1 |         "bytes": 0
sfmweiboharvester_1 |     }
sfmweiboharvester_1 | }
```

## Possible Solutions
Slow down the collection frequency and keep running for more data.

**Comment by justinlittman** [comment]
So that looks like you got some bad data from the API.  I would suggest
catching and logging the json parse error, but allow the harvest to
continue.

**Comment by Tanych** [comment]
Catching the 404 and >500 error and retry 30 times, if all fail then stop!
