### ISSUE TITLE
Warc Record Decode Error

### ISSUE THREAD

**Issue by Tanych** [gwu-libraries/sfm-weibo-harvester#5]
## Weibo Warc records encoding with gzip or deflate 
* ERROR LOG
```python
Traceback (most recent call last):
  File "weibo_warc_iter.py", line 20, in <module>
    WeiboWarcIter.main(WeiboWarcIter)
  File "/opt/sfm-utils/sfmutils/warc_iter.py", line 136, in main
    print_item_type=args.print_item_type)
  File "/opt/sfm-utils/sfmutils/warc_iter.py", line 59, in print_iter
    for item_type, item in self.iter(limit_item_types=limit_item_types):
  File "/opt/sfm-utils/sfmutils/warc_iter.py", line 31, in iter
    for record in f:
  File "/opt/sfm-utils/sfmutils/warc.py", line 51, in __iter__
    print http_response.data
  File "/usr/local/lib/python2.7/site-packages/urllib3/response.py", line 166, in data
    return self.read(cache_content=True)
  File "/usr/local/lib/python2.7/site-packages/urllib3/response.py", line 316, in read
    data = self._decode(data, decode_content, flush_decoder)
  File "/usr/local/lib/python2.7/site-packages/urllib3/response.py", line 197, in _decode
    "failed to decode it." % content_encoding, e)
urllib3.exceptions.DecodeError: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing: incorrect header check',))
```

* The related code
[sfm-utils/warc.py](https://github.com/gwu-libraries/sfm-utils/blob/master/sfmutils/warc.py)
```python
start_line, http_headers = self.read_http_start_line_and_headers(payload)
if start_line.startswith("HTTP/1.1 200 OK"):
    http_response = HTTPResponse(body=payload, headers=http_headers, status=200, version=1.1,
                                                 reason="OK", preload_content=False)
   yield WARCResponseRecord(record.header, http_response)
   # Setting this so _warc_reader can read to end of record.
   self._restore_current_payload(save_payload)
```
The [HTTPResponse](http://urllib3.readthedocs.org/en/1.1/helpers.html#module-urllib3.request) (urllib3 version 1.12) can't decode the weibo http response payload. I am trying to using the following method:
**zlib**  :
* to (de-)compress deflate format, use wbits = -zlib.MAX_WBITS
* to (de-)compress zlib format, use wbits = zlib.MAX_WBITS
* to (de-)compress gzip format, use wbits = zlib.MAX_WBITS | 16

```python
zlib.decompress
```
However, **It won't work!**
Also, there are some discussions about this similar error.
[GZip decode error] (https://github.com/shazow/urllib3/issues/206)

## Weibo Warc records without encoding
The warc I collected at Jan 26, 2016, It wasn't encoded with gzip. When I try to get the JSON with warc iteration. It occurs the following error:
```python
No handlers could be found for logger "sfmutils.warc_iter"
Traceback (most recent call last):
  File "weibo_warc_iter.py", line 20, in <module>
    WeiboWarcIter.main(WeiboWarcIter)
  File "/opt/sfm-utils/sfmutils/warc_iter.py", line 136, in main
    print_item_type=args.print_item_type)
  File "/opt/sfm-utils/sfmutils/warc_iter.py", line 59, in print_iter
    for item_type, item in self.iter(limit_item_types=limit_item_types):
  File "/opt/sfm-utils/sfmutils/warc_iter.py", line 47, in iter
    for item_type, item in self._item_iter(record.url, json_obj):
UnboundLocalError: local variable 'json_obj' referenced before assignment
```
and the raw data for the HTTP response is:
```http
WARC/1.0
WARC-Record-ID: <urn:uuid:8ffc8d6b-704b-4a5c-9682-b730e6294a70>
WARC-Type: warcinfo
WARC-Filename: test_3-20160127161055380-00000-151-69ab86cb7c4a-8000.warc.gz
WARC-Date: 2016-01-27T16:10:55Z
Content-Type: application/warc-fields
Content-Length: 117

software: warcprox 1.4-20151211140803-7fb596d
hostname: 69ab86cb7c4a
ip: 172.17.0.3
format: WARC File Format 1.0


WARC/1.0
WARC-Type: response
WARC-Record-ID: <urn:uuid:c7c87e05-71bb-4bc5-929b-f352ad0f957a>
WARC-Date: 2016-01-27T16:10:55Z
WARC-Target-URI: https://api.weibo.com/2/statuses/friends_timeline.json?access_token=2.00kQCxKGpYiFYDc41039481c0wvwei&count=100&page=1
WARC-IP-Address: 114.134.80.166
Content-Type: application/http;msgtype=response
Content-Length: 388866
WARC-Block-Digest: sha1:043322e13db3d32d34789fdd892558a69e3727f7
WARC-Payload-Digest: sha1:f4b12f93876c6acd53447001c601b45e0e31f60b

HTTP/1.1 200 OK
Server: nginx/1.6.1
Date: Wed, 27 Jan 2016 16:10:51 GMT
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Api-Server-IP: 10.75.5.67
SINA-LB: aGEuMTY4LmcxLmh5ZHMubGIuc2luYW5vZGUuY29t
SINA-TS: OTIwOWMzNjggMCAzNyAzNyA0IDU4OAo=

2c70
{"statuses":[{"created_at":"Wed Jan 27 23:59:09 +0800 2016","id":3936047643339619,"mid":"3936047643339619","idstr":"3936047643339619","text":"【#莫扎特的音乐治病#能平复情绪？[音乐盒]】他毕生创作了700余部作品，《费加罗的婚礼》《唐璜》《魔笛》等成永恒经典。有专家做试验，在给病人播放莫扎特《D大调双钢琴奏鸣曲》，36名病人中有29人的症状得到了减轻。1756年的今天，音乐大师莫扎特诞生。今天，不妨去试听一曲？http://t.cn/R298uzZ","textLength":277,"source_allowclick":0,"source_type":1,"source":"<a href=\"http://app.weibo.com/t/feed/2O2xZO\" rel=\"nofollow\">人民网微博</a>","favorited":false,"truncated":false,"in_reply_to_status_id":"","in_reply_to_user_id":"","in_reply_to_screen_name":"","pic_urls":[],"geo":null,"user"
.......
```

**Comment by Tanych** [comment]
## Reasons for decode error 
Weibo HTTP response raw data:

* sample 1

WARC/1.0^M
WARC-Type: response^M
WARC-Record-ID: <urn:uuid:5eda27a7-dbb5-48ca-8147-8c5f7c59549e>^M
WARC-Date: 2016-02-14T06:34:08Z^M
WARC-Target-URI: https://api.weibo.com/2/statuses/friends_timeline.json?access_token=2.00kQCxKGpYiFYDc41039481c0wvwei&count=100&page=1&since_id=3942423010574165^M
WARC-IP-Address: 114.134.80.166^M
Content-Type: application/http;msgtype=response^M
Content-Length: **8835**^M
WARC-Block-Digest: sha1:9affc207dc83e1aacf882f9aa1a2210d0a4a667a^M
WARC-Payload-Digest: sha1:5580a8d130b0f9d95b23abd5f5044940dc91ce12^M
^M

HTTP/1.1 200 OK^M
Server: nginx/1.6.1^M
Date: Sun, 14 Feb 2016 06:34:06 GMT^M
Content-Type: application/json;charset=UTF-8^M
Transfer-Encoding: chunked^M
Connection: keep-alive^M
Api-Server-IP: 10.75.5.58^M
Content-Encoding: gzip^M
Vary: Accept-Encoding^M
SINA-LB: aGEuMTY4LmcxLmh5ZHMubGIuc2luYW5vZGUuY29t^M
SINA-TS: OTcwOWMzNjggMCAzNiAzNiA1IDQ5MQo=^M
^M
211f^M
^_<8b>^H^@^@^@^@^@^@^@ì}yS^[É<96>ïWáá^?fb<8c>©¬½<88><99>

**Response Body HEX**
**0X32:0X31:0X31:0X66:0X0D:0X0A:**0X1F:0X8B:0X08:0X00:0X00:0X00:0X00:0X00:0X00:0X00:0XEC:0X7D:0X79:0X53

**0X32:0X31:0X31:0X66:0X0D:0X0A:** is the length of **8479** related to the conten-length. 
**0X1F:0X8B** is the header for GZIP format start.

* sample 2

WARC/1.0^M
WARC-Type: response^M
WARC-Record-ID: <urn:uuid:3537dccc-1bda-4870-a389-c5ab0031b644>^M
WARC-Date: 2016-02-15T06:04:19Z^M
WARC-Target-URI: https://api.weibo.com/2/statuses/friends_timeline.json?access_token=2.00kQCxKGpYiFYDc41039481c0wvwei&count=100&page=1&since_id=3942777257541194^M
WARC-IP-Address: 114.134.80.166^M
Content-Type: application/http;msgtype=response^M
Content-Length: 3184^M
WARC-Block-Digest: sha1:7fef7e9b2d4d6335df451f70dd804882c10dadc3^M
WARC-Payload-Digest: sha1:8aed0910235abf534783f025f7f8d9a6f9ab0c63^M
^M
HTTP/1.1 200 OK^M
Server: nginx/1.6.1^M
Date: Mon, 15 Feb 2016 06:04:15 GMT^M
Content-Type: application/json;charset=UTF-8^M
Transfer-Encoding: chunked^M
Connection: keep-alive^M
Api-Server-IP: 10.75.5.64^M
Content-Encoding: gzip^M
Vary: Accept-Encoding^M
SINA-LB: aGEuMTY4LmcxLmh5ZHMubGIuc2luYW5vZGUuY29t^M
SINA-TS: OTUwOWMzNjggMCAzNiAzNiA2IDQ1OQo=^M
^M
b0d^M
^_<8b>^H^@^@^@^@^@^@^@ìZ[SÛH^Vþ+.½.Á­

**Response Body HEX**
**0X62:0X30:0X64:0X0D:0X0A:**0X1F:0X8B:0X08:0X00:0X00:0X00:0X00:0X00:0X00:0X00:0XEC:0X5A
**0X62:0X30:0X64:0X0D:0X0A:** is 2829.

So when the HTTPResponse to decode the body data, but the data won't start with **0X1F:0X8B**. It would fail to check the header.

**Comment by Tanych** [comment]
Using urllib3 HTTPResponse read_chunked to decode the body part.
It need modify the code in https://github.com/gwu-libraries/sfm-utils/blob/master/sfmutils/warc_iter.py and 
https://github.com/gwu-libraries/sfm-utils/blob/master/sfmutils/warc.py
A pull request will be in the next session.

**Comment by Tanych** [comment]
Chunked encoding refer https://github.com/gwu-libraries/sfm-utils/commit/ff1b592d0c7adc5284cafd8b9e6726060f891d14
